# frozen_string_literal: true
source 'https://rubygems.org'
source 'https://packages.shopify.io/shopify/gems'

gemspec

group :deployment do
  gem 'package_cloud'
end

group :development do
  gem 'mobiletools', git: 'git@github.com:Shopify/mobiletools.git'
end

group :test do
  gem "minitest", "~> 5.11"
  gem "minitest-reporters"
  gem "mocha"
end
