# frozen_string_literal: true
source 'https://rubygems.org'

gemspec

group :deployment do
  gem 'package_cloud'
end

group :test do
  gem "minitest", "~> 5.11"
  gem "minitest-reporters"
  gem "mocha"
end
